### ISSUE TITLE
HTTP Build Error

### ISSUE THREAD

**Issue by dhje0ng** [devolo/dlan-greenphy-sdk#23]
py ../HTTP/bin/makefsdata.py
Traceback (most recent call last):
  File "C:\Users\guest\Desktop\mobility-charging\dlan-greenphy-sdk\Applications\HTTP\bin\makefsdata.py", line 6, in <module>
    from css_html_js_minify import html_minify, js_minify, css_minify
  File "C:\Users\guest\AppData\Local\Programs\Python\Python310\lib\site-packages\css_html_js_minify\__init__.py", line 11, in <module>
    from .minify import (process_single_html_file, process_single_js_file,
  File "C:\Users\guest\AppData\Local\Programs\Python\Python310\lib\site-packages\css_html_js_minify\minify.py", line 28, in <module>
    from anglerfish import (check_encoding, check_folder, make_logger,
  File "C:\Users\guest\AppData\Local\Programs\Python\Python310\lib\site-packages\anglerfish\__init__.py", line 32, in <module>
    from anglerfish.get_clipboard import get_clipboard  # noqa
  File "C:\Users\guest\AppData\Local\Programs\Python\Python310\lib\site-packages\anglerfish\get_clipboard.py", line 18, in <module>
    Clipboard = NamedTuple("Clipboard", fields=(("copy", callable),
  File "C:\Users\guest\AppData\Local\Programs\Python\Python310\lib\typing.py", line 2323, in NamedTuple
    return _make_nmtuple(typename, fields, module=module)
  File "C:\Users\guest\AppData\Local\Programs\Python\Python310\lib\typing.py", line 2248, in _make_nmtuple
    types = {n: _type_check(t, f"field {n} annotation must be a type")
  File "C:\Users\guest\AppData\Local\Programs\Python\Python310\lib\typing.py", line 2248, in <dictcomp>
    types = {n: _type_check(t, f"field {n} annotation must be a type")
  File "C:\Users\guest\AppData\Local\Programs\Python\Python310\lib\typing.py", line 176, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: field fields annotation must be a type Got (('copy', <built-in function callable>), ('paste', <built-in function callable>)).
make[1]: [makefile:61: pre-build] Error 1 (ignored)
 
css-html-js-minify : 2.2.2
beautifoulsoup4 : 4.11.1
OS : Windows 10
MCUXPresso : 11.5.1

**Comment by dhje0ng** [comment]
It is solved by upgrading css-html-js-minify to 2.5.5.

But I get the following error:

FileNotFoundError: [Errno 2] No such file or directory: '..\\src\\httpd-fsdata.c'
make[1]: [makefile:61: pre-build] Error 1 (ignored)

**Comment by dhje0ng** [comment]
This error occurs on Windows OS. Since the path cannot be found, it can be used by modifying it to an absolute path.
